### ISSUE TITLE
Links containing a dot [ . ] return 51 (not found)

### ISSUE THREAD

**Issue by arakimo** [RealMelkor/Vgmi#1]
On some gemini pages, relative links to other pages may use `.` or `..`

Vgmi does not appear to be able to load such links correctly.

For example, the following would return error 51:
`=> ./2022/08/05/comparing-multi-factor-authentication-methods/ Comparing Multi-Factor Authentication Methods`

However, the following link to an RSS feed successfully accessed the download:
`=> ./atom.xml Atom Feed`

The following error message was displayed:
`Not found (51 : Not found gemini://nicksphere.ch/./2022/08/05/comparing-multi-factor-authentication-methods)`

Some capsules structure internal links this way, rendering vgmi unable to navigate them.
(encountered the issue here: gemini://nicksphere.ch )

**Comment by RealMelkor** [comment]
Thanks for the bug report, I just pushed a fix for this, Vgmi should now support  those kind of links correctly. I tested using the capsule mentioned(gemini://nicksphere.ch) and it seems to work fine overall.

**Comment by arakimo** [comment]
Just checked it out, it works great now. Thanks :)
