### ISSUE TITLE
[Feature Request] Support for protocol proxies

### ISSUE THREAD

**Issue by xplshn** [RealMelkor/Vgmi#4]
Will protocol proxies ever be supported? Like for example HTTP/s to Gemini? (one example of such proxy is gemini://gemi.dev/stargate.gmi)

:)

**Comment by xplshn** [comment]
Handlers could be added in a way so that the user can set XXX.handler.open = "glow %f"
 and XXX1.handler.view = "chafa %f"
 
 where .view would open the program in a different buffer and .open would simply call the program with the provided arguments
 
 note: chafa is an image viewer, glow is a markdown reader
 
 Maybe this is too much complexity to add to such a small program, but it'd be great to have

**Comment by RealMelkor** [comment]
I added a configuration option for http protocol proxies in about:config. I made it empty by default since the default behavior of Vgmi is to open http/https links with xdg-open.

**Comment by xplshn** [comment]
Thank you! Do I leave this issue open?

**Comment by RealMelkor** [comment]
We can close it
