### ISSUE TITLE
[Suggestion] Allow to open unknown file formats by asking the user what handler to use with %f for file or %u for URL

### ISSUE THREAD

**Issue by xplshn** [RealMelkor/Vgmi#5]

**Comment by RealMelkor** [comment]
I added the ":exec" command, which allows to open the last downloaded file.
The command open the file using a launcher, the default launcher is xdg-open, but it can be changed in about:config.
The default behavior is to launch the program in another window. If you want to run the program in the terminal instead, you will need to disable the sandbox and set the value of launcher.terminal to 1 in about:config.
It's still an experimental feature, but it seemed to work fine with the chafa image viewer.

**Comment by xplshn** [comment]
How does that work for TTYs?

**Comment by RealMelkor** [comment]
To run it in TTYs you will need to disable the sandbox and set the value of launcher.terminal to 1 in about:config.
You can use something like that [https://github.com/BachoSeven/mimi](https://github.com/BachoSeven/mimi) for your launcher if you don't want to install xdg-open directly. 
I tested it with chafa as the image viewer and it works in the TTYs.
To open a file with the launcher from Vgmi, you need to use the command ":exec", it will download the current page and launch the file using the launcher specified by launcher.executable in about:config.

**Comment by xplshn** [comment]
okay, thanks
