### ISSUE TITLE
Vgmi creates ~/Downloads

### ISSUE THREAD

**Issue by xplshn** [RealMelkor/Vgmi#6]
Why? Another method could be using an env variable, for example:

VGMI_DOWNLOADS_DIR

Assigning the value of that env variable to a variable and if the variable is "" then setting the download dir to a default one. Also, a config parameter for this and other directories that vgmi might access would be great

**Comment by RealMelkor** [comment]
I added an option to set a custom downloads path in about:config.
The reason it creates the downloads directory on startup is to allow the directory in the sandbox.
All the other files written by Vgmi are in a directory that is located by default in ~/.config/vgmi.
The config directory can be changed using the environment variable XDG_CONFIG_HOME.

**Comment by xplshn** [comment]
Thanks!
