### ISSUE TITLE
[Q] Changing the image viewer?

### ISSUE THREAD

**Issue by xplshn** [RealMelkor/Vgmi#7]
Can the user set a custom image viewer? I suggested handlers, which would allow to get rid of the STB dependency and it'd be more Unixy to use external programs for the image functionality, but is there already another way?

**Comment by RealMelkor** [comment]
The image viewer won't be compiled into Vgmi if the stb_image.h file is not found at compile time, so if you don't want the image viewer you can simply compile it without it.
To use an external image viewer, see the ":exec" command in #5.

**Comment by xplshn** [comment]
Thank you for all this!
