### ISSUE TITLE
[Bug?] Since GPM support was added, I can no longer select/copy text in TTYs

### ISSUE THREAD

**Issue by xplshn** [RealMelkor/Vgmi#8]

**Comment by RealMelkor** [comment]
When a program use GPM to read mouse input, GPM copy/paste stops working. The same behavior can be seen in Elinks.

**Comment by xplshn** [comment]
Yes, but is there no way to add it back? Its such a bummer... I mainly use TUI programs and the framebuffer, its not often that I am forced to open a X session. But I understand it is probably not worth it to add a feature only I use, and its also YOUR project, so thanks anyways
